import { useEffect, useState } from 'react';
import { ArrowRight, Check } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { useStore } from '../context/StoreContext';
import { money } from '../lib/catalog';

const API = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
export default function Checkout() {
  const { cart, setCart, user } = useStore(); const navigate = useNavigate(); const [paying, setPaying] = useState(false); const [error, setError] = useState(''); const paid = new URLSearchParams(location.search).get('success') === 'true'; const total = cart.reduce((sum, item) => sum + item.price * item.qty, 0);
  useEffect(() => { if (paid) setCart([]); }, [paid, setCart]);
  const checkout = async (event) => { event.preventDefault(); if (!user) return navigate('/login'); setPaying(true); try { const response = await fetch(`${API}/payments/create-checkout-session`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${user.token}` }, body: JSON.stringify({ items: cart }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); location.assign(data.url); } catch (requestError) { setError(requestError.message); setPaying(false); } };
  if (paid) return <main className="shell grid min-h-[60vh] place-items-center"><div className="text-center"><div className="mx-auto grid size-16 place-items-center rounded-full bg-lime"><Check/></div><h1 className="mt-5 text-4xl font-black">Payment received.</h1><p className="mt-3 text-zinc-500">Thank you. Stripe has confirmed your payment.</p><Link to="/" className="btn-dark mt-7">Back to storefront</Link></div></main>;
  return <main className="shell py-10"><h1 className="text-4xl font-black tracking-tight">Secure checkout</h1><div className="mt-8 grid gap-10 lg:grid-cols-[1fr_380px]"><form onSubmit={checkout} className="space-y-6 rounded-3xl bg-white p-6 shadow-sm"><h2 className="font-black">Shipping details</h2>{['Email', 'Full name', 'Address', 'City', 'Postal code'].map((label) => <input required placeholder={label} key={label} className="w-full border-b border-zinc-200 py-3 text-sm"/>)}<h2 className="pt-3 font-black">Payment</h2><div className="rounded-xl border border-ink bg-zinc-50 p-4 text-sm font-semibold">Pay securely with Stripe <span className="float-right text-zinc-400">Cards & wallets</span></div>{error && <p className="text-sm text-red-600">{error}</p>}<button disabled={paying || !cart.length} className="btn-dark w-full disabled:opacity-50">{paying ? 'Connecting to Stripe…' : `Pay ${money(total)} with Stripe`} <ArrowRight size={17}/></button></form><aside className="h-fit rounded-3xl bg-ink p-6 text-white"><h2 className="font-black">Order summary</h2><div className="mt-5 space-y-4">{cart.map((item, index) => <div key={index} className="flex gap-3 text-sm"><img src={item.image} className="size-12 rounded-lg object-cover"/><span className="flex-1">{item.name} × {item.qty}</span><b>{money(item.price * item.qty)}</b></div>)}</div><div className="mt-6 border-t border-white/15 pt-5"><div className="flex justify-between text-lg font-black"><span>Total</span><span>{money(total)}</span></div></div></aside></div></main>;
}
