import { motion } from 'framer-motion';
import { ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import ProductCard from '../components/ProductCard';
import { getFallbackProducts } from '../lib/catalog';

export default function Home() {
  const arrivals = getFallbackProducts('', 'All', 'featured', 4);
  return <><section className="shell pb-12 pt-5"><div className="relative min-h-[530px] overflow-hidden rounded-[2rem] bg-ink px-7 py-10 text-white md:px-16"><div className="absolute right-0 top-0 h-full w-3/5 bg-gradient-to-l from-zinc-600/40"/><motion.img initial={{ scale: 1.08 }} animate={{ scale: 1 }} transition={{ duration: 1.2 }} src="https://images.unsplash.com/photo-1495555961986-6d4c1ecb7be3?auto=format&fit=crop&w=1400&q=90" className="absolute right-0 top-0 h-full w-full object-cover opacity-65 md:w-3/5"/><div className="relative z-10 flex max-w-xl flex-col items-start"><span className="eyebrow rounded-full border border-white/25 bg-white/10 px-3 py-2 text-white">01 / New Season</span><h1 className="mt-14 text-5xl font-black leading-[.92] tracking-[-.075em] md:text-7xl">Made for your<br/><span className="text-lime">everyday motion.</span></h1><p className="mt-6 max-w-sm text-sm leading-6 text-zinc-300">Thoughtful objects and essential performance layers for a life in forward motion.</p><Link className="btn mt-8 bg-lime text-ink hover:bg-white" to="/shop">Explore the collection <ArrowRight size={17}/></Link></div><div className="absolute bottom-6 right-6 z-10 rounded-2xl border border-white/20 bg-black/25 p-4 backdrop-blur-md"><p className="font-mono text-[10px] tracking-widest text-zinc-300">ELEVATED ESSENTIALS</p><p className="mt-1 text-sm font-bold">Designed with intent.</p></div></div></section><section className="shell py-10"><div className="mb-7 flex items-end justify-between"><div><p className="eyebrow">Curated for motion</p><h2 className="mt-2 text-3xl font-black tracking-[-.05em]">New arrivals</h2></div><Link to="/shop" className="btn border border-zinc-300">View all <ArrowRight size={16}/></Link></div><div className="grid grid-cols-2 gap-x-4 gap-y-8 md:grid-cols-4">{arrivals.map((product) => <ProductCard product={product} key={product._id}/>)}</div></section><section className="shell py-12"><div className="grid gap-4 rounded-3xl bg-zinc-200 p-7 md:grid-cols-3"><div><p className="eyebrow">The Velora standard</p><h2 className="mt-3 text-3xl font-black tracking-tight">Less, but better.</h2></div><p className="text-sm leading-6 text-zinc-600">Every object begins with a question: how can this make the everyday feel more considered?</p><p className="text-sm leading-6 text-zinc-600">Built to be used hard and lived in fully, then return tomorrow ready for more.</p></div></section></>;
}
