import { AnimatePresence, motion } from 'framer-motion';
import { Check, Minus, Plus, Trash2, X, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { money } from '../lib/catalog';
import { useStore } from '../context/StoreContext';

export default function CartDrawer() {
  const { cart, setCart, cartOpen, setCartOpen } = useStore();
  const subtotal = cart.reduce((total, item) => total + item.price * item.qty, 0);
  const remaining = Math.max(0, 150 - subtotal);
  const changeQuantity = (index, change) => setCart((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, qty: Math.max(1, item.qty + change) } : item));

  return <AnimatePresence>{cartOpen && <><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setCartOpen(false)} className="fixed inset-0 z-40 bg-black/25 backdrop-blur-sm"/><motion.aside initial={{ x: '100%' }} animate={{ x: 0 }} exit={{ x: '100%' }} transition={{ type: 'spring', damping: 28, stiffness: 250 }} className="fixed right-0 top-0 z-50 flex h-full w-full max-w-md flex-col bg-[#fcfcfa] p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-2xl font-black tracking-tight">Your bag <span className="text-zinc-400">({cart.length})</span></h2><button onClick={() => setCartOpen(false)} className="rounded-full p-2 hover:bg-zinc-100"><X/></button></div><div className="mt-6 rounded-xl bg-lime/50 p-4 text-sm font-semibold">{remaining ? <><b>{money(remaining)}</b> away from complimentary shipping <div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white"><div className="h-full bg-ink" style={{ width: `${Math.min(100, subtotal / 150 * 100)}%` }}/></div></> : <><Check className="mr-2 inline" size={16}/>You unlocked complimentary shipping.</>}</div><div className="mt-5 flex-1 space-y-5 overflow-auto">{cart.length === 0 ? <p className="pt-12 text-center text-zinc-500">Your bag is waiting for its first find.</p> : cart.map((item, index) => <motion.div layout key={`${item._id}-${index}`} className="flex gap-4"><img src={item.image} className="size-20 rounded-xl object-cover"/><div className="flex-1"><div className="flex justify-between gap-3"><div><p className="font-bold">{item.name}</p><p className="text-xs text-zinc-500">{item.size || ''} {item.color || ''}</p></div><b>{money(item.price * item.qty)}</b></div><div className="mt-3 flex items-center justify-between"><div className="flex items-center rounded-full border border-zinc-200"><button onClick={() => changeQuantity(index, -1)} className="p-1.5"><Minus size={14}/></button><span className="w-7 text-center text-sm">{item.qty}</span><button onClick={() => changeQuantity(index, 1)} className="p-1.5"><Plus size={14}/></button></div><button onClick={() => setCart((items) => items.filter((_, itemIndex) => itemIndex !== index))} className="text-zinc-400 hover:text-red-500"><Trash2 size={16}/></button></div></div></motion.div>)}</div><div className="border-t border-zinc-200 pt-5"><div className="mb-4 flex justify-between text-lg font-black"><span>Subtotal</span><span>{money(subtotal)}</span></div><Link to="/checkout" onClick={() => setCartOpen(false)} className="btn-dark w-full">Secure checkout <ArrowRight size={17}/></Link></div></motion.aside></>}</AnimatePresence>;
}
